#!/bin/sh
blacklist=(/usr/bin/bluetoothctl
/usr/bin/btmgmt
/usr/bin/ctstat
/usr/bin/dbus-monitor
/usr/bin/dbus-update-activation-environment
/usr/bin/driverless
/usr/bin/ex
/usr/bin/l2test
/usr/bin/less
/usr/bin/lnstat
/usr/bin/mpris-proxy
/usr/bin/obexctl
/usr/bin/pager
/usr/bin/pkcheck
/usr/bin/pkttyagent
/usr/bin/rctest
/usr/bin/resize
/usr/bin/rtstat
/usr/bin/rview
/usr/bin/rvim
/usr/bin/scanimage
/usr/bin/su
/usr/bin/systemctl
/usr/bin/systemd-cgls
/usr/bin/tload
/usr/bin/tset
/usr/bin/view
/usr/bin/vim.basic
/usr/bin/vimdiff
/usr/bin/vim.tiny
/bin/bluetoothctl
/bin/btmgmt
/bin/ctstat
/bin/dbus-monitor
/bin/dbus-update-activation-environment
/bin/driverless
/bin/ex
/bin/l2test
/bin/less
/bin/lnstat
/bin/mpris-proxy
/bin/obexctl
/bin/pager
/bin/pkcheck
/bin/pkttyagent
/bin/rctest
/bin/resize
/bin/rtstat
/bin/rview
/bin/rvim
/bin/scanimage
/bin/su
/bin/systemctl
/bin/systemd-cgls
/bin/tload
/bin/view
/bin/vim.basic
/bin/vimdiff
/bin/vim.tiny
)
